name: Setup Python CI
description: Setup Python CI boilerplate

inputs:
  python-version:
    description: Python version
    required: false
    default: ""
  enable-cache:
    description: Enable UV cache
    required: false
    default: "true"
  cache-python:
    description: Cache Python installation
    required: false
    default: "true"

runs:
  using: composite
  steps:
    - run: echo "Setup Python CI loaded successfully"
      shell: bash
    - uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411
      with:
        egress-policy: audit
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      with:
        persist-credentials: false
    - uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39
      with:
        enable-cache: ${{ inputs.enable-cache }}
        cache-python: ${{ inputs.cache-python }}
        python-version: ${{ inputs.python-version }}
