name: Bump dependencies

on:
  schedule:
    - cron: '0 6 * * 1'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  bump:
    uses: damien-robotsix/robotsix-mill/.github/workflows/deps-bump.yml@a317d51ad25be89194d55f220164819807d549f1 # v0.0.1
    secrets: inherit
