name: Docs

on:
  push:
    branches: [main]

jobs:
  docs:
    permissions:
      contents: write
    uses: damien-robotsix/robotsix-github-workflows/.github/workflows/python-docs.yml@77e10e286717cfe0eeb6b8d9ce985f3794236d15  # main
