name: Lint workflows

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  lint-workflows:
    uses: damien-robotsix/robotsix-github-workflows/.github/workflows/lint-workflows.yml@6d737634940626eed0bec995c8e462892730e610  # main
    permissions:
      contents: read
    with:
      run-actionlint: true
      run-zizmor: true
