name: Lint workflows

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  lint-workflows:
    uses: damien-robotsix/robotsix-github-workflows/.github/workflows/lint-workflows.yml@293d6295e4200fc0ee4a6ded19dc2f098c652869  # main
    permissions:
      contents: read
    with:
      run-actionlint: true
      run-zizmor: true
