name: Release

on:
  push:
    branches: ['main']
    tags: ['v*']
  workflow_dispatch:

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false

jobs:
  publish:
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write
    uses: damien-robotsix/robotsix-mill/.github/workflows/docker-release.yml@a317d51ad25be89194d55f220164819807d549f1 # v0.0.1
    secrets: inherit
